### ISSUE TITLE
Python API knowledge

### ISSUE THREAD

**Issue by llevitis** [neurolibre/boutiques-tutorial#13]
Similar to this issue #11 - there are a few places where it's unclear what the expected level of familiarity with Python APIs is. It would be helpful to the reader if this expectation were clarified at the top of the notebook or if more verbose explanations were given throughout the notebook. 

For instance, the user is shown how to use the bosh example command both on the command line and with the API. Instead of saying "Of course, this can all be reproduced with the Python API, for instance", there could be an explanation about arguments having to be passed in the same order on the command line as they are when using the Python API. 

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/17363738/60739213-179daf00-9f2f-11e9-9d2c-d83441aececa.png">

Likewise, it might be helpful to be more verbose when explaining that `descriptor2func` is a library within the overarching Boutiques module, and it has its own set of commands. The python function created by passing a Zenodo DOI to the command `function` is the main function corresponding to the tool associated with the DOI . 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/17363738/60739207-0fde0a80-9f2f-11e9-8ce2-3f13db962098.png">

**Comment by glatard** [comment]
Thanks for the suggestion, it makes a lot of sense!
