### ISSUE TITLE
review #1

### ISSUE THREAD

**Issue by lunebellec** [neurolibre/boutiques-tutorial#6]
Thank you @llevitis for agreeing to review this submission. You can find our guidelines for review [here](https://github.com/neurolibre/submit/blob/master/REVIEWER.md). When your review is completed, please leave a comment on this issue saying so. If there are unresolved issues that you believe to be impeding the acceptance of the repository, please list them here.

**Comment by lunebellec** [comment]
so far issue #13 is pending in this review.

**Comment by lunebellec** [comment]
@llevitis please confirm that there is no other outstanding issues besides #13

**Comment by llevitis** [comment]
@pbellec - I have merged #14, and I think the tutorial is good to go!

**Comment by lunebellec** [comment]
that is awesome!! I think this is our first accepted submission. Congratulations @glatard @llevitis @martinagvilas and @ltetrel . We'll take it from there.
