### ISSUE TITLE
review #2

### ISSUE THREAD

**Issue by lunebellec** [neurolibre/boutiques-tutorial#7]
Thank you @martinagvilas  for agreeing to review this submission. You can find our guidelines for review [here](https://github.com/neurolibre/submit/blob/master/REVIEWER.md). When your review is completed, please leave a comment on this issue saying so. If there are unresolved issues that you believe to be impeding the acceptance of the repository, please list them here.

**Comment by lunebellec** [comment]
currently issues #8 #9 #10 and #11 have been identified through this review.

**Comment by lunebellec** [comment]
@martinagvilas please check out this pull request https://github.com/neurolibre/boutiques-tutorial/pull/12 and let @glatard know if this addresses all of your concern.

**Comment by martinagvilas** [comment]
@glatard has addressed all my concerns and I believe this tutorial provides a clear and concise overview of boutiques, and puts into evidence the advantages of using this framework. It is easy to read, it is logically organized into relevant sections, and it is of appropriate length.

Thank you for giving me the opportunity to review it.

**Comment by lunebellec** [comment]
Thanks a lot @martinagvilas for taking the time to review this work, and thanks @glatard for addressing all the issues in a timely fashion. I am closing this review.
