### ISSUE TITLE
CalledProcessError when running bet -h

### ISSUE THREAD

**Issue by martinagvilas** [neurolibre/boutiques-tutorial#8]
Hi! Thanks for submitting this very useful tutorial of boutiques.

Here goes my first issue:

When running the command `bet -h` in the tutorial I obtain a CalledProcessError. Specifically, I get the following output (after the printout of the command line options of bet):

![image](https://user-images.githubusercontent.com/37339384/60103721-62b20800-9760-11e9-8718-808f679c703b.png)

**Comment by glatard** [comment]
Hi! This is because `bet -h` returns a non-zero exit code. I will update to `bet -h || true`, unless you have a better suggestion.

**Comment by martinagvilas** [comment]
I think that is good enough for the purposes of the tutorial. Thanks!
