### ISSUE TITLE
FutureWarning when running nifti_plotter

### ISSUE THREAD

**Issue by martinagvilas** [neurolibre/boutiques-tutorial#9]
When executing `nifti_plotter` I get a Future Warning. In detail: 

![image](https://user-images.githubusercontent.com/37339384/60106128-ed950180-9764-11e9-9067-d18c81a99a60.png)

**Comment by glatard** [comment]
This is something that sometimes happens in NiftiViewer and disappears when executed again. Shall I just recommend to re-run the cell if this happens?

**Comment by martinagvilas** [comment]
That's a good idea. Such recommendation might be useful for those not familiar with Nifti.
